spring.application.name=job-microservice
server.port=8082
#spring.datasource.url=jdbc:h2:mem:test
spring.datasource.url=jdbc:postgresql://localhost:5432/jobdb
spring.datasource.username=postgres
spring.datasource.password=saso@2005
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
company.service.url=http://COMPANY-MICROSERVICE
review.service.url=http://REVIEW-MICROSERVICE

# Eureka configuration
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.healthcheck.enabled=true
eureka.instance.lease-renewal-interval-in-seconds=10
eureka.instance.lease-expiration-duration-in-seconds=30

